### ISSUE TITLE
21_descriptor_layout: fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by mewmew** [vkngwrapper/vulkan-tutorial#2]
I continued to run the various steps of the vulkan--tutorial, but ran into this issue on step `21_descriptor_layout`.

I'm using the same laptop as reported in #1, namely running Arch Linux and tried with X11 and Wayland rendering servers.

Note, all steps up until 21 work (except for step 7).

The output of running step `21_descriptor_layout` is:

```
$./21_descriptor_layout 
2023/04/24 12:07:04 [Error Validation] - Validation Error: [ VUID-vkCmdDrawIndexed-None-02697 ] Object 0: handle = 0xd175b40000000013, type = VK_OBJECT_TYPE_PIPELINE; Object 1: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_PIPELINE_LAYOUT; | MessageID = 0x9888fef3 | vkCmdDrawIndexed(): The VkPipeline 0xd175b40000000013[] (created with VkPipelineLayout 0xdcc8fd0000000012[]) statically uses descriptor set (index #0) which is not compatible with the currently bound descriptor set's pipeline layout (VkPipelineLayout 0x0[]) The Vulkan spec states: For each set n that is statically used by the VkPipeline bound to the pipeline bind point used by this command, a descriptor set must have been bound to n at the same pipeline bind point, with a VkPipelineLayout that is compatible for set n, with the VkPipelineLayout used to create the current VkPipeline, as described in Pipeline Layout Compatibility (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdDrawIndexed-None-02697)
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x54 pc=0x7f6e844bad87]

runtime stack:
runtime.throw({0x888d2c?, 0x7f6e77898d28?})
	/home/u/go/src/runtime/panic.go:1075 +0x5c fp=0x7fffc52b0c80 sp=0x7fffc52b0c50 pc=0x4421dc
runtime.sigpanic()
	/home/u/go/src/runtime/signal_unix.go:821 +0x3e9 fp=0x7fffc52b0ce0 sp=0x7fffc52b0c80 pc=0x457b29

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x75a740, 0xc0001e5c98)
	/home/u/go/src/runtime/cgocall.go:157 +0x51 fp=0xc0001e5c70 sp=0xc0001e5c38 pc=0x4115d1
github.com/vkngwrapper/core/v2/driver._Cfunc_cgoCmdDrawIndexed(0x7f6e77299510, 0x1aacd70, 0x6, 0x1, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:4080 +0x45 fp=0xc0001e5c98 sp=0xc0001e5c70 pc=0x6b7b65
github.com/vkngwrapper/core/v2/driver.(*vulkanDriver).VkCmdDrawIndexed.func1(0x10000006cbdfa?, 0x7f6e8c6b76f8?, 0x0?, 0x0?, 0xb5d58?, 0xc0?, 0x6e4cfd?)
	/home/u/goget/pkg/mod/github.com/vkngwrapper/core/v2@v2.1.2/driver/bridge.go:1271 +0x98 fp=0xc0001e5cf8 sp=0xc0001e5c98 pc=0x6cd298
github.com/vkngwrapper/core/v2/driver.(*vulkanDriver).VkCmdDrawIndexed(0x6e4c40?, 0xc0000f85c0?, 0x8?, 0x0?, 0x7b4e00?, 0x0?, 0x0?)
	/home/u/goget/pkg/mod/github.com/vkngwrapper/core/v2@v2.1.2/driver/bridge.go:1271 +0x1a fp=0xc0001e5d30 sp=0xc0001e5cf8 pc=0x6cd19a
github.com/vkngwrapper/core/v2/core1_0.(*VulkanCommandBuffer).CmdDrawIndexed(0xc00018a600, 0x909d50?, 0xc000181050?, 0x1?, 0x0?, 0x182af8?)
	/home/u/goget/pkg/mod/github.com/vkngwrapper/core/v2@v2.1.2/core1_0/command_buffer.go:123 +0x3c fp=0xc0001e5d68 sp=0xc0001e5d30 pc=0x6e48dc
main.(*HelloTriangleApplication).createCommandBuffers(0xc0000ff400)
	/home/u/Desktop/vulkan-tutorial/steps/21_descriptor_layout/main.go:1202 +0x3fe fp=0xc0001e5ed0 sp=0xc0001e5d68 pc=0x73d5de
main.(*HelloTriangleApplication).initVulkan(0xc0000ff400?)
	/home/u/Desktop/vulkan-tutorial/steps/21_descriptor_layout/main.go:255 +0x145 fp=0xc0001e5ef0 sp=0xc0001e5ed0 pc=0x7384c5
main.(*HelloTriangleApplication).Run(0xc0000ff400)
	/home/u/Desktop/vulkan-tutorial/steps/21_descriptor_layout/main.go:151 +0x46 fp=0xc0001e5f38 sp=0xc0001e5ef0 pc=0x738166
main.main()
	/home/u/Desktop/vulkan-tutorial/steps/21_descriptor_layout/main.go:1462 +0x1f fp=0xc0001e5f80 sp=0xc0001e5f38 pc=0x73eadf
runtime.main()
	/home/u/go/src/runtime/proc.go:250 +0x207 fp=0xc0001e5fe0 sp=0xc0001e5f80 pc=0x444947
runtime.goexit()
	/home/u/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001e5fe8 sp=0xc0001e5fe0 pc=0x472de1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/u/go/src/runtime/proc.go:381 +0xd0 fp=0xc00004afb0 sp=0xc00004af90 pc=0x444d30
runtime.goparkunlock(...)
	/home/u/go/src/runtime/proc.go:387
runtime.forcegchelper()
	/home/u/go/src/runtime/proc.go:305 +0xa5 fp=0xc00004afe0 sp=0xc00004afb0 pc=0x444ba5
runtime.goexit()
	/home/u/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00004afe8 sp=0xc00004afe0 pc=0x472de1
created by runtime.init.6
	/home/u/go/src/runtime/proc.go:293 +0x1a

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/u/go/src/runtime/proc.go:381 +0xd0 fp=0xc00004b780 sp=0xc00004b760 pc=0x444d30
runtime.goparkunlock(...)
	/home/u/go/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
	/home/u/go/src/runtime/mgcsweep.go:278 +0x88 fp=0xc00004b7c8 sp=0xc00004b780 pc=0x431b08
runtime.gcenable.func1()
	/home/u/go/src/runtime/mgc.go:178 +0x25 fp=0xc00004b7e0 sp=0xc00004b7c8 pc=0x427365
runtime.goexit()
	/home/u/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00004b7e8 sp=0xc00004b7e0 pc=0x472de1
created by runtime.gcenable
	/home/u/go/src/runtime/mgc.go:178 +0x6a

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000070000?, 0x9013a0?, 0x1?, 0x0?, 0x0?)
	/home/u/go/src/runtime/proc.go:381 +0xd0 fp=0xc00004bf70 sp=0xc00004bf50 pc=0x444d30
runtime.goparkunlock(...)
	/home/u/go/src/runtime/proc.go:387
runtime.(*scavengerState).park(0xbec4e0)
	/home/u/go/src/runtime/mgcscavenge.go:399 +0x49 fp=0xc00004bfa0 sp=0xc00004bf70 pc=0x42fb09
runtime.bgscavenge(0x0?)
	/home/u/go/src/runtime/mgcscavenge.go:627 +0x3c fp=0xc00004bfc8 sp=0xc00004bfa0 pc=0x43009c
runtime.gcenable.func2()
	/home/u/go/src/runtime/mgc.go:179 +0x25 fp=0xc00004bfe0 sp=0xc00004bfc8 pc=0x427305
runtime.goexit()
	/home/u/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00004bfe8 sp=0xc00004bfe0 pc=0x472de1
created by runtime.gcenable
	/home/u/go/src/runtime/mgc.go:179 +0xaa

goroutine 18 [finalizer wait]:
runtime.gopark(0x7f6eb4a115b8?, 0x1a0?, 0x70?, 0xa7?, 0x45161e?)
	/home/u/go/src/runtime/proc.go:381 +0xd0 fp=0xc00004a628 sp=0xc00004a608 pc=0x444d30
runtime.runfinq()
	/home/u/go/src/runtime/mfinal.go:193 +0xf8 fp=0xc00004a7e0 sp=0xc00004a628 pc=0x426418
runtime.goexit()
	/home/u/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00004a7e8 sp=0xc00004a7e0 pc=0x472de1
created by runtime.createfing
	/home/u/go/src/runtime/mfinal.go:163 +0x3d
```

**Comment by mewmew** [comment]
GDB back trace:

```
$ gdb ./21_descriptor_layout
(gdb) r
2023/04/24 23:28:16 [Error Validation] - Validation Error: [ VUID-vkCmdDrawIndexed-None-02697 ] Object 0: handle = 0xd175b40000000013, type = VK_OBJECT_TYPE_PIPELINE; Object 1: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_PIPELINE_LAYOUT; | MessageID = 0x9888fef3 | vkCmdDrawIndexed(): The VkPipeline 0xd175b40000000013[] (created with VkPipelineLayout 0xdcc8fd0000000012[]) statically uses descriptor set (index #0) which is not compatible with the currently bound descriptor set's pipeline layout (VkPipelineLayout 0x0[]) The Vulkan spec states: For each set n that is statically used by the VkPipeline bound to the pipeline bind point used by this command, a descriptor set must have been bound to n at the same pipeline bind point, with a VkPipelineLayout that is compatible for set n, with the VkPipelineLayout used to create the current VkPipeline, as described in Pipeline Layout Compatibility (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdDrawIndexed-None-02697)

Thread 1 "21_descriptor_l" received signal SIGSEGV, Segmentation fault.
0x00007fffb64bad87 in ?? () from /usr/lib/libvulkan_intel.so
(gdb) bt
#0  0x00007fffb64bad87 in ?? () from /usr/lib/libvulkan_intel.so
#1  0x00007fffb64bb53b in ?? () from /usr/lib/libvulkan_intel.so
#2  0x00007fffb64c4a3e in ?? () from /usr/lib/libvulkan_intel.so
#3  0x00007fffb5699718 in DispatchCmdDrawIndexed (firstInstance=0, vertexOffset=0, firstIndex=0, instanceCount=1, 
    indexCount=6, commandBuffer=0x195f5f0)
    at /usr/src/debug/vulkan-validation-layers/Vulkan-ValidationLayers-sdk-1.3.243.0/layers/generated/layer_chassis_dispatch.cpp:3425
#4  vulkan_layer_chassis::CmdDrawIndexed (commandBuffer=0x195f5f0, indexCount=6, instanceCount=1, firstIndex=0, 
    vertexOffset=0, firstInstance=0)
    at /usr/src/debug/vulkan-validation-layers/Vulkan-ValidationLayers-sdk-1.3.243.0/layers/generated/chassis.cpp:3078
#5  0x000000000075a767 in _cgo_11a601e9dd6c_Cfunc_cgoCmdDrawIndexed (v=<optimized out>)
    at /tmp/go-build/cgo-gcc-prolog:601
#6  0x0000000000472aa4 in runtime.asmcgocall () at /home/u/go/src/runtime/asm_amd64.s:848
#7  0x0000000000c03ec0 in ?? ()
#8  0x0000000000000001 in ?? ()
#9  0x000000000044c800 in runtime.exitsyscallfast (oldp=<optimized out>, ~r0=<optimized out>)
    at /home/u/go/src/runtime/proc.go:4013
#10 0x00000000004756bf in runtime.newproc (fn=0x470d2f <runtime.rt0_go+303>) at <autogenerated>:1
#11 0x0000000000470da5 in runtime.mstart () at /home/u/go/src/runtime/asm_amd64.s:394
#12 0x0000000000470d2f in runtime.rt0_go () at /home/u/go/src/runtime/asm_amd64.s:358
#13 0x0000000000000001 in ?? ()
#14 0x00007fffffffe628 in ?? ()
#15 0x0000000000000000 in ?? ()
```

**Comment by CannibalVox** [comment]
Oh this one is reliable! That's a relief.

**Comment by CannibalVox** [comment]
I suspect that the validation error is related to the crash, since it's crashing in the driver. This step doesn't work for me, with the same validation errors, but doesn't crash. The next couple steps fail on purpose for being incomplete so I think I just assumed it was supposed to do that when I was smoke testing, but I see in the tutorial that this step is supposed to display a rectangle. Will get fixed ASAP.

**Comment by CannibalVox** [comment]
OK so the problem is that vulkan-tutorial.com reorganized. They added a new step 16 "frames in flight", so step 20 became step 21, which was the source of my confusion.

Step 20 (shows as 21 in the tutorial), which shows a rectangle, still works.  Step 21 has never worked because step 22 needs to be completed before the code is valid. On most graphics cards, it just prints a validation error and shows a black screen, but it looks like integrated intel cards actually crash. I probably need to update the tutorial to match what's now on the site but this doesn't seem like something I can fix.

**Comment by CannibalVox** [comment]
Looks like it's this issue: https://github.com/Overv/VulkanTutorial/issues/194

At the very least I guess I can add a readme to the chapter

**Comment by mewmew** [comment]
> Looks like it's this issue: [Overv/VulkanTutorial#194](https://github.com/Overv/VulkanTutorial/issues/194)
> 
> At the very least I guess I can add a readme to the chapter

Wow, you're quick : )
